import './style.scss'
import { onHandleRoute } from "helper/route";
import { helperCre } from "helper/helperCreat";
import Prof from 'img/prof.png'
import Search from 'img/search.png'
import Menu from '/img/ham.png'
import Cross from '/img/cross.png'
const Index = () => {
    const header = helperCre('header', 'header')
    const container = helperCre('div', 'container header__org')
    const wrap = helperCre('div', 'header__wrap')
    const logoNav = helperCre('nav', 'header__logo-nav')
    const logoW = helperCre('a', 'header__logo-wrap', null, '/')
    logoW.addEventListener('click', onHandleRoute)
    const logo = helperCre('img', 'header__logo', null, null, 'https://technext.github.io/anime/img/logo.png')
    const pWrap = helperCre('nav', 'header__pages-wrap')
    const a1 = helperCre('a', 'header__link', 'Homepage', '/')
    a1.addEventListener('click', onHandleRoute)
    const a2 = helperCre('a', 'header__link', 'Anime', '/anime')
    a2.addEventListener('click', onHandleRoute)
    const a3 = helperCre('a', 'header__link', 'Product', '/product')
    a3.addEventListener('click', onHandleRoute)
    const a4 = helperCre('a', 'header__link', '404', '/404')
    a4.addEventListener('click', onHandleRoute)
    const rSide = helperCre('div', 'header__right-side')
    const searchWrap = helperCre('div', 'header__search-wrap')
    const form = helperCre('form', 'header__form')
    const search = helperCre('input', 'header__search')
    search.placeholder = 'Search'
    const searchIc = helperCre('img', 'header__search-icon', null, null, Search)
    const searchA = helperCre('a', '', null, '/search')
    searchA.addEventListener('click', onHandleRoute)
    const prof = helperCre('img', 'header__prof', null, null, Prof)
    const profLink = helperCre('a', 'header__prof-link', null, !localStorage.getItem('CurUser') ? '/auth' : '/profile')
    profLink.addEventListener('click', onHandleRoute)
    const nav3 = helperCre('nav', '')
    const hidNav = helperCre('nav', 'container header__mob-nav')
    const hidBut = helperCre('a', 'header__mob-btn', 'Menu', '#')
    const hidUl = helperCre('ul', 'header__mob-menu')
    const hidEx = helperCre('img', 'header__mob-exit', null, null, Cross)
    const hidLi1 = helperCre('li', 'header__mob-li')
    const hidLi2 = helperCre('li', 'header__mob-li')
    const hidLi3 = helperCre('li', 'header__mob-li')
    const hidLi4 = helperCre('li', 'header__mob-li')
    hidBut.addEventListener('click', (e) => {e.preventDefault(); hidClose.hidden = !hidClose.hidden})
    const hidA1 = helperCre('a', 'header__mob-link', null, '/')
    hidA1.addEventListener('click', onHandleRoute)
    const hidT1 = helperCre('p', 'header__mob-link-text', 'Homepage')
    const hidA2 = helperCre('a', 'header__mob-link', null, '/anime')
    hidA2.addEventListener('click', onHandleRoute)
    const hidT2 = helperCre('p', 'header__mob-link-text', 'About')
    const hidA3 = helperCre('a', 'header__mob-link', null, '/product')
    hidA3.addEventListener('click', onHandleRoute)
    const hidT3 = helperCre('p', 'header__mob-link-text', 'Product')
    const hidA4 = helperCre('a', 'header__mob-link', null, '/404')
    hidA4.addEventListener('click', onHandleRoute)
    const hidT4 = helperCre('p', 'header__mob-link-text', '404')
    const hamPic = helperCre('img', 'header__mob-pic', null, null, Menu)
    const hidClose = helperCre('div', 'header__mob-close')
    hidClose.hidden = true
    hidUl.addEventListener('click', (e) => {e.preventDefault(); hidClose.hidden = !hidClose.hidden})
    hidEx.addEventListener('click', (e) => {e.preventDefault(); hidClose.hidden = !hidClose.hidden})
    logoW.append(logo)
    logoNav.append(logoW)
    wrap.append(logoNav)
    pWrap.append(a1)
    pWrap.append(a2)
    pWrap.append(a3)
    pWrap.append(a4)
    wrap.append(pWrap)
    form.append(search)
    searchWrap.append(form)
    searchA.append(searchIc)
    searchWrap.append(searchA)
    rSide.append(searchWrap)
    hidBut.append(hamPic)
    profLink.append(prof)
    hidA1.append(hidT1)
    hidLi1.append(hidA1)
    hidUl.append(hidLi1)
    hidA2.append(hidT2)
    hidLi2.append(hidA2)
    hidUl.append(hidLi2)
    hidA3.append(hidT3)
    hidLi3.append(hidA3)
    hidUl.append(hidLi3)
    hidA4.append(hidT4)
    hidLi4.append(hidA4)
    hidUl.append(hidLi4)
    hidNav.append(hidEx)
    hidNav.append(hidUl)
    hidClose.append(hidNav)
    nav3.append(profLink)
    rSide.append(nav3)
    rSide.append(hidBut)
    rSide.append(hidClose)
    container.append(wrap)
    container.append(rSide)
    header.append(container)
    return header
}
export default Index;